### ISSUE TITLE
Integration tests fail

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar-adapters#12]
**Describe the bug**

Integration test fail

**To Reproduce**
```
cd tests
mvn clean install -DintegrationTests
```

get
```
[INFO] Running TestSuite
[ERROR] Tests run: 29, Failures: 1, Errors: 0, Skipped: 28, Time elapsed: 0.792 s <<< FAILURE! - in TestSuite
[ERROR] setup(org.apache.pulsar.tests.integration.compat.kafka.PulsarKafkaProducerThreadSafeTest)  Time elapsed: 0.662 s  <<< FAILURE!
java.lang.NullPointerException
	at org.apache.pulsar.tests.integration.compat.kafka.PulsarKafkaProducerThreadSafeTest.getPlainTextServiceUrl(PulsarKafkaProducerThreadSafeTest.java:37)
	at org.apache.pulsar.tests.integration.compat.kafka.PulsarKafkaProducerThreadSafeTest.setup(PulsarKafkaProducerThreadSafeTest.java:43)
```

**Expected behavior**

Tests running and passing

**Comment by lhotari** [comment]
Fixed by #19 and #22
